#lang racket

(require eopl)
(require "datatype.scm")
(require "environments.scm")
(require "utils.scm")

(provide value-of-program value-of)

;; value-of-program : Program * Env -> ExpVal
(define value-of-program
  (lambda (pgm env)
    (cases program pgm
      (a-program (exp)
                 (value-of exp env)))))

;; value-of : Exp * Env -> ExpVal
(define value-of
  (lambda (exp env)
    (debug "Evaluating exp: ~s, env: ~s~n" exp env)
    (cases expression exp
      (const-exp (num) (num-val num))
      (var-exp (var) (apply-env env var))
      (add-exp (exp1 exp2)
        (let ((val1 (value-of exp1 env))
              (val2 (value-of exp2 env)))
          (let ((num1 (expval->num val1))
                (num2 (expval->num val2)))
            (num-val (+ num1 num2)))))
      (diff-exp (exp1 exp2)
        (let ((val1 (value-of exp1 env))
              (val2 (value-of exp2 env)))
          (let ((num1 (expval->num val1))
                (num2 (expval->num val2)))
            (num-val (- num1 num2)))))
      (zero?-exp (exp)
        (let ((val (value-of exp env)))
          (let ((num (expval->num val)))
            (if (zero? num)
              (bool-val #t)
              (bool-val #f)))))
      (less-than-exp (exp1 exp2)
        (let ((val1 (value-of exp1 env))
              (val2 (value-of exp2 env)))
          (let ((num1 (expval->num val1))
                (num2 (expval->num val2)))
            (if (< num1 num2)
              (bool-val #t)
              (bool-val #f)))))
      (not-exp (exp)
        (let ((val (value-of exp env)))
          (if (expval->bool val)
            (bool-val #f)
            (bool-val #t))))
      (if-exp (exp1 exp2 exp3)
        (let ((val (value-of exp1 env)))
          (if (expval->bool val)
            (value-of exp2 env)
            (value-of exp3 env))))
      (else (error 'value-of "Unsupported expression: ~s" exp)))))